# Reference: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - deadcode
    # - depguard
    - errcheck
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - maligned
    - misspell
    - nakedret
    # - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/hypnoglow/terraform-provider-oryhydra)
  gocritic:
    disabled-checks:
      - singleCaseSwitch

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: Error return value of `d.Set` is not checked
