name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Install dependencies
        run: |
          go mod download
          go mod vendor

      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31

      - name: Build
        run: |
          go build -o ./bin/terraform-provider-oryhydra
