name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3.2.1
        with:
          cache: true
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: |
          go mod download
          go mod vendor

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@34ea557550c84ea665cae5c61c3b084feac7e042 # v5.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef # v3.0.0
        with:
          version: latest
          args: release --rm-dist --config=.github/goreleaser.yaml
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
